/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'auditProgress': MotiaStream<{ type: 'audit-started' | 'pr-data-fetched' | 'scan-complete' | 'ai-review-complete' | 'dependency-risk-found' | 'audit-finalized'; sessionId: string; data: Record<string, unknown>; timestamp: string }>
  }

  interface Handlers {
    'StaticAnalysis': EventHandler<{ sessionId: string; prDetails: unknown; prFiles: Array<unknown>; repository: { owner: string; repo: string }; prNumber: number }, { topic: 'scan-complete'; data: never }>
    'FinalAggregation': EventHandler<{ sessionId: string; aiReview: unknown; analysisResult: unknown; prDetails: unknown; prFiles: Array<unknown>; repository: { owner: string; repo: string }; prNumber: number }, never>
    'FetchPRData': EventHandler<{ sessionId: string; config: { repositoryUrl: string; prNumber: number }; repository: { owner: string; repo: string }; prNumber: number }, { topic: 'pr-data-fetched'; data: { sessionId: string; prDetails: unknown; prFiles: Array<unknown>; repository: { owner: string; repo: string }; prNumber: number } }>
    'AICodeReviewer': EventHandler<never, { topic: 'ai-review-complete'; data: { sessionId: string; aiReview: unknown; analysisResult: unknown; prDetails: unknown; prFiles: Array<unknown>; repository: { owner: string; repo: string }; prNumber: number } }>
    'StartAudit': ApiRouteHandler<{ repositoryUrl: string; openRouterKey: string; prNumber?: number }, ApiResponse<200, { sessionId: string; message: string; prCount: number }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'audit-started'; data: { sessionId: string; config: { repositoryUrl: string; prNumber: number }; repository: { owner: string; repo: string }; prNumber: number } }>
    'GetSession': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; config: { repositoryUrl: string; openRouterKey: string; prNumber?: number }; status: 'initializing' | 'running' | 'completed' | 'failed'; steps: Array<{ stepId: string; stepName: string; status: 'idle' | 'running' | 'success' | 'failed'; startTime?: string; endTime?: string; error?: string; data?: Record<string, unknown> }>; currentStep?: string; createdAt: string; updatedAt: string }> | ApiResponse<404, { error: string }>, never>
    'GetPullRequests': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { pullRequests: Array<{ number: number; title: string; html_url: string; user: { login: string; avatar_url: string }; created_at: string; updated_at: string }>; totalCount: number }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, never>
    'GetAnalysisDetails': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { analysisType: string; data: unknown; sessionId: string; timestamp: string }> | ApiResponse<404, { error: string; message: string }> | ApiResponse<500, { error: string; message: string }>, never>
  }
    
}